language: ruby
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- bundle exec rails db:create db:migrate
script:
- bundle exec rspec spec
notifications:
  email: false
deploy:
  provider: heroku
  app: gram-2-grandma
  run: bundle exec rails db:migrate
  api_key:
    secure: FleNFBe9YlD1mPTjSNKAAayxZEw/D/SZcBgYHmCDAoPx1KBWZ+cm73mbXPpHIVIB+9LS1jqSMXhbAQ3PSbwNDdDSz4kIMVSp4/A0Fxge1jB1rPVJ4BAhvWIZiGhupqHYYfiPvWGcX88h+Y6boYiIk5s0FkWewoEirgVOOw+jd4EmMI0puSLH4cJk1j+l1FCs9cvN2bNBTx9rcm5QXYuJ1mF/G1uR57YdxntDgrgz9neZQ+YtZcscAyZdM9obQgkRQsc3q87OK+oEMOw0F3HH3YU9B/YaVPTSHU7dwWnRDG1VLzYYM7WlKeRjfZHoEoi4U1UZoTMX8YIMoPnZ8egvca8iXimhGW/KbsvvSI6fIbEeUxnBYdAuFcky9BzqcviL8LbX7PafOhq5rksExKQU/oKSwnHNsQmys8dG/jViN6i2aZin1J1BipVycSgj7SgKYcA4uTT7iY+56xwnPL7BNhiO8KiuFEpENGFoJikEdMQOSBXlA7THmB+e75lGvWaEHWYNYMPYPvYdIXj0Ns2Tja6dCkHZQDQNbPIeGU96qMic8OuXgx/PNyh009EHAYoOX6ntSaUyM0hqsABz3qlzoRbrE2VgSVRtyjlC2IEkBHSnt11uByWrfnl9HaQ5pdGx76IlWVvdG9iga+jDDwT1URPfuSReCXrcoVfvhSaNi8k=
